In [13]:
library(tidyverse)

all_data <- readRDS("datas_and_notebooks/final_datas/all_data_joined.rds")
all_data

     date       site plot subplot   diversity id   species
1    2024-05-26 a    ac32 ac32-i    2         276  lindera reflexa
2    2024-05-26 a    ac32 ac32-i    2         327  lindera reflexa
3    2024-05-26 a    ac32 ac32-i    2         597  lindera reflexa
4    2024-05-26 a    ac32 ac32-i    2         1658 seedling
5    2024-05-26 a    ac32 ac32-i    2         1520 quercus sp.
6    2024-05-26 a    ac32 ac32-i    2         1526 seedling
7    2024-05-26 a    ac32 ac32-ii   2         666  quercus fabri
8    2024-05-26 a    ac32 ac32-ii   2         333  syzygium buxifolium
9    2024-05-26 a    ac32 ac32-iii  2         660  adinandra millettii
10   2024-05-26 a    ac32 ac32-iii  2         667  buddleja lindleyana
11   2024-05-26 a    ac32 ac32-iv   2         716  camellia sinensis
12   2024-05-26 a    ac32 ac32-iv   2         716  camellia sinensis
13   2024-05-26 a    ac32 ac32-iv   2         349  ilex suaveolens
14   2024-05-26 a    ac32 ac32-iv   2         349  ilex suaveolens
15   2024-05-26 a    ac32 ac32-iv   2         1740 ilex suaveolens
16   2024-05-26 a    ac32 ac32-iv   2         1420 seedling
17   2024-05-26 a    ac32 ac32-iv   2         1592 recruit
18   2024-05-20 a    ae31 ae31-i    1         92   quercus serrata
19   2024-05-20 a    ae31 ae31-i    1         340  quercus serrata
20   2024-05-20 a    ae31 ae31-ii   1         250  dalbergia hupeana
21   2024-05-20 a    ae31 ae31-iii  1         290  seedling
22   2024-05-20 a    ae31 ae31-iii  1         408  ilex pubescens
23   2024-05-20 a    ae31 ae31-iii  1         493  ilex pubescens
24   2024-05-20 a    ae31 ae31-iii  1         248  rhododendron simsii
25   2024-05-20 a    ae31 ae31-iii  1         364  rhododendron simsii
26   2024-05-20 a    ae31 ae31-iii  1         211b rhododendron simsii
27   2024-05-20 a    ae31 ae31-iii  1         1697 seedling
28   2024-05-20 a    ae31 ae31-iv   1         421  camellia japonica
29   2024-05-20 a    ae31 ae31-iv   1         308  loropetalum chinense
30   2024-05-20 a    ae31 ae31-iv   1         308  loropetalum chinense
⋮    ⋮          ⋮    ⋮    ⋮         ⋮         ⋮    ⋮
3995 2023-06-17 b    bw11 bw11-ii   1         483  castanopsis sclerophylla
3996 2023-06-17 b    bw11 bw11-iii  1         412  rhaphiolepis indica
3997 2023-06-17 b    bw11 bw11-iii  1         254  ilex pubescens
3998 2023-06-17 b    bw11 bw11-iv   1         71   loropetalum chinense
3999 2023-06-17 b    bw11 bw11-iv   1         350  castanopsis fargesii
4000 2023-06-17 b    bw11 bw11-iv   1         124  rhaphiolepis indica
4001 2023-06-17 b    bw11 bw11-iv   1         98   castanopsis fargesii
4002 2023-06-17 b    bw11 bw11-iv   1         17   lindera glauca
4003 2023-06-17 b    bw11 bw11-iv   1         15   eurya muricata
4004 2023-06-17 b    bw11 bw11-iv   1         325  adinandra millettii
4005 2023-06-17 b    bw11 bw11-iv   1         467  eurya muricata
4006 2023-06-17 b    bw11 bw11-iv   1         357  eurya muricata
4007 2023-06-17 b    bx21 bx21-ii.o 1         164  rhus chinensis
4008 2023-06-17 b    bx21 bx21-ii.o 1         604  itea omeiensis
4009 2023-06-17 b    bx21 bx21-ii.o 1         631  camellia japonica
4010 2023-06-17 b    bx21 bx21-ii.o 1         653  alniphyllum fortunei
4011 2023-06-17 b    bx21 bx21-ii.o 1         658a euonymus maxiflorus
4012 2023-06-17 b    bx21 bx21-ii   1         370  rhus chinensis
4013 2023-06-17 b    bx21 bx21-ii   1         579  adinandra millettii
4014 2023-06-17 b    bx21 bx21-ii   1         206  adinandra millettii
4015 2023-06-17 b    bx21 bx21-ii   1         620  eurya muricata
4016 2023-06-17 b    bx21 bx21-iii  1         702  castanopsis sclerophylla
4017 2023-06-17 b    bx21 bx21-iii  1         306  castanopsis sclerophylla
4018 2023-06-17 b    bx21 bx21-iii  1         718  castanopsis sclerophylla
4019 2023-06-17 b    bx21 bx21-iii  1         383  itea omeiensis
4020 2023-06-17 b    bx21 bx21-iv   1         574  eurya muricata
4021 2023-06-17 b    bx21 bx21-iv   1         456  adinandra millettii
4022 2023-06-17 b    bx21 bx21-iv   1         242  alniphyllum fortunei
4023 2023-06-17 b    bx21 bx21-iv   1         767  eurya muricata
4024 2023-06-17 b    bx21 bx21-iv   1         699  rhus chinensis
     genus        family           growth_form ⋯ soil_h20_all soil_ph_k_cl_all
1    lindera      lauraceae        shrub/tree  ⋯ 4.673        3.735
2    lindera      lauraceae        shrub/tree  ⋯ 4.673        3.735
3    lindera      lauraceae        shrub/tree  ⋯ 4.673        3.735
4    NA           NA               NA          ⋯ 4.673        3.735
5    NA           NA               NA          ⋯ 4.673        3.735
6    NA           NA               NA          ⋯ 4.673        3.735
7    quercus      fagaceae         tree        ⋯ 4.673        3.735
8    syzygium     myrtaceae        shrub/tree  ⋯ 4.673        3.735
9    adinandra    pentaphylacaceae shrub/tree  ⋯ 4.673        3.735
10   buddleja     scrophulariaceae shrub       ⋯ 4.673        3.735
11   camellia     theaceae         shrub/tree  ⋯ 4.673        3.735
12   nyssa        nyssaceae        tree        ⋯ 4.673        3.735
13   ilex         aquifoliaceae    shrub/tree  ⋯ 4.673        3.735
14   osmanthus    oleaceae         shrub/tree  ⋯ 4.673        3.735
15   ilex         aquifoliaceae    shrub/tree  ⋯ 4.673        3.735
16   unknown      unknown          unknown     ⋯ 4.673        3.735
17   NA           NA               NA          ⋯ 4.673        3.735
18   quercus      fagaceae         tree        ⋯ 4.808        3.839
19   quercus      fagaceae         tree        ⋯ 4.808        3.839
20   dalbergia    fabaceae         tree        ⋯ 4.808        3.839
21   quercus      fagaceae         tree        ⋯ 4.808        3.839
22   ilex         aquifoliaceae    shrub/tree  ⋯ 4.808        3.839
23   ilex         aquifoliaceae    shrub/tree  ⋯ 4.808        3.839
24   rhododendron ericaceae        shrub/tree  ⋯ 4.808        3.839
25   rhododendron ericaceae        shrub/tree  ⋯ 4.808        3.839
26   NA           NA               NA          ⋯ 4.808        3.839
27   unknown      unknown          unknown     ⋯ 4.808        3.839
28   camellia     theaceae         shrub/tree  ⋯ 4.808        3.839
29   loropetalum  hamamelidaceae   shrub       ⋯ 4.808        3.839
30   rhododendron ericaceae        shrub/tree  ⋯ 4.808        3.839
⋮    ⋮            ⋮                ⋮           ⋱ ⋮            ⋮
3995 castanopsis  fagaceae         tree        ⋯ 5.093        4.003
3996 rhaphiolepis rosaceae         shrub/tree  ⋯ 5.093        4.003
3997 ilex         aquifoliaceae    shrub/tree  ⋯ 5.093        4.003
3998 loropetalum  hamamelidaceae   shrub       ⋯ 5.093        4.003
3999 castanopsis  fagaceae         tree        ⋯ 5.093        4.003
4000 rhaphiolepis rosaceae         shrub/tree  ⋯ 5.093        4.003
4001 castanopsis  fagaceae         tree        ⋯ 5.093        4.003
4002 lindera      lauraceae        shrub/tree  ⋯ 5.093        4.003
4003 eurya        pentaphylacaceae shrub/tree  ⋯ 5.093        4.003
4004 adinandra    pentaphylacaceae shrub/tree  ⋯ 5.093        4.003
4005 eurya        pentaphylacaceae shrub/tree  ⋯ 5.093        4.003
4006 eurya        pentaphylacaceae shrub/tree  ⋯ 5.093        4.003
4007 rhus         anacardiaceae    shrub/tree  ⋯ 4.570        3.721
4008 itea         iteaceae         shrub       ⋯ 4.570        3.721
4009 camellia     theaceae         shrub/tree  ⋯ 4.570        3.721
4010 alniphyllum  styracaceae      tree        ⋯ 4.570        3.721
4011 euonymus     celastraceae     shrub/tree  ⋯ 4.570        3.721
4012 rhus         anacardiaceae    shrub/tree  ⋯ 4.570        3.721
4013 adinandra    pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4014 adinandra    pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4015 eurya        pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4016 castanopsis  fagaceae         tree        ⋯ 4.570        3.721
4017 castanopsis  fagaceae         tree        ⋯ 4.570        3.721
4018 castanopsis  fagaceae         tree        ⋯ 4.570        3.721
4019 itea         iteaceae         shrub       ⋯ 4.570        3.721
4020 eurya        pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4021 adinandra    pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4022 alniphyllum  styracaceae      tree        ⋯ 4.570        3.721
4023 eurya        pentaphylacaceae shrub/tree  ⋯ 4.570        3.721
4024 rhus         anacardiaceae    shrub/tree  ⋯ 4.570        3.721
     soil_n_all soil_c_all soil_c_n_all soil_h20 soil_ph_k_cl soil_n
1    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
2    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
3    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
4    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
5    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
6    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
7    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
8    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
9    0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
10   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
11   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
12   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
13   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
14   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
15   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
16   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
17   0.14042845 1.7618909  12.001016    4.805    3.785        0.2144261
18   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
19   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
20   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
21   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
22   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
23   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
24   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
25   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
26   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
27   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
28   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
29   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
30   0.09608315 0.9799343   9.112079    4.820    3.855        0.1846543
⋮    ⋮          ⋮          ⋮            ⋮        ⋮            ⋮
3995 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
3996 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
3997 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
3998 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
3999 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4000 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4001 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4002 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4003 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4004 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4005 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4006 0.1577054  1.762769   10.96104     4.925    3.885        0.16260716
4007 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4008 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4009 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4010 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4011 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4012 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4013 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4014 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4015 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4016 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4017 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4018 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4019 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4020 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4021 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4022 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4023 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
4024 0.1191558  1.302245   10.33149     4.500    3.725        0.08644888
     soil_c    soil_c_n
1    3.191298  14.88641
2    3.191298  14.88641
3    3.191298  14.88641
4    3.191298  14.88641
5    3.191298  14.88641
6    3.191298  14.88641
7    3.191298  14.88641
8    3.191298  14.88641
9    3.191298  14.88641
10   3.191298  14.88641
11   3.191298  14.88641
12   3.191298  14.88641
13   3.191298  14.88641
14   3.191298  14.88641
15   3.191298  14.88641
16   3.191298  14.88641
17   3.191298  14.88641
18   2.394872  12.62730
19   2.394872  12.62730
20   2.394872  12.62730
21   2.394872  12.62730
22   2.394872  12.62730
23   2.394872  12.62730
24   2.394872  12.62730
25   2.394872  12.62730
26   2.394872  12.62730
27   2.394872  12.62730
28   2.394872  12.62730
29   2.394872  12.62730
30   2.394872  12.62730
⋮    ⋮         ⋮
3995 1.9018477 10.912727
3996 1.9018477 10.912727
3997 1.9018477 10.912727
3998 1.9018477 10.912727
3999 1.9018477 10.912727
4000 1.9018477 10.912727
4001 1.9018477 10.912727
4002 1.9018477 10.912727
4003 1.9018477 10.912727
4004 1.9018477 10.912727
4005 1.9018477 10.912727
4006 1.9018477 10.912727
4007 0.7477469  8.592937
4008 0.7477469  8.592937
4009 0.7477469  8.592937
4010 0.7477469  8.592937
4011 0.7477469  8.592937
4012 0.7477469  8.592937
4013 0.7477469  8.592937
4014 0.7477469  8.592937
4015 0.7477469  8.592937
4016 0.7477469  8.592937
4017 0.7477469  8.592937
4018 0.7477469  8.592937
4019 0.7477469  8.592937
4020 0.7477469  8.592937
4021 0.7477469  8.592937
4022 0.7477469  8.592937
4023 0.7477469  8.592937
4024 0.7477469  8.592937

In [14]:
all_data |> 
filter(id == 290)

  date       site plot subplot    diversity id  species
1 2024-05-20 a    ae31 ae31-iii   1         290 seedling
2 2024-09-26 b    bj29 bj29-iii.o 8         290 castanopsis sclerophylla
3 2023-09-07 a    ae31 ae31-iii   1         290 quercus sp.
4 2023-09-27 b    bj29 bj29-iii.o 8         290 castanopsis sclerophylla
5 2023-06-18 a    ae31 ae31-iii   1         290 quercus sp.
  genus       family   growth_form ⋯ soil_h20_all soil_ph_k_cl_all soil_n_all
1 quercus     fagaceae tree        ⋯ 4.808        3.839            0.09608315
2 castanopsis fagaceae tree        ⋯ 4.646        3.712            0.17647652
3 quercus     fagaceae tree        ⋯ 4.808        3.839            0.09608315
4 castanopsis fagaceae tree        ⋯ 4.646        3.712            0.17647652
5 quercus     fagaceae tree        ⋯ 4.808        3.839            0.09608315
  soil_c_all soil_c_n_all soil_h20 soil_ph_k_cl soil_n    soil_c   soil_c_n
1 0.9799343   9.112079    4.82     3.855        0.1846543 2.394872 12.62730
2 2.0971568  11.456782    4.62     3.600        0.1819413 2.283359 11.03555
3 0.9799343   9.112079    4.82     3.855        0.1846543 2.394872 12.62730
4 2.0971568  11.456782    4.62     3.600        0.1819413 2.283359 11.03555
5 0.9799343   9.112079    4.82     3.855        0.1846543 2.394872 12.62730

In [15]:
all_data |> 
 distinct(species, genus, family)

    species                   genus           family
1   lindera reflexa           lindera         lauraceae
2   seedling                  NA              NA
3   quercus sp.               NA              NA
4   quercus fabri             quercus         fagaceae
5   syzygium buxifolium       syzygium        myrtaceae
6   adinandra millettii       adinandra       pentaphylacaceae
7   buddleja lindleyana       buddleja        scrophulariaceae
8   camellia sinensis         camellia        theaceae
9   camellia sinensis         nyssa           nyssaceae
10  ilex suaveolens           ilex            aquifoliaceae
11  ilex suaveolens           osmanthus       oleaceae
12  seedling                  unknown         unknown
13  recruit                   NA              NA
14  quercus serrata           quercus         fagaceae
15  dalbergia hupeana         dalbergia       fabaceae
16  seedling                  quercus         fagaceae
17  ilex pubescens            ilex            aquifoliaceae
18  rhododendron simsii       rhododendron    ericaceae
19  rhododendron simsii       NA              NA
20  camellia japonica         camellia        theaceae
21  loropetalum chinense      loropetalum     hamamelidaceae
22  loropetalum chinense      rhododendron    ericaceae
23  lithocarpus glaber        lithocarpus     fagaceae
24  eurya muricata            NA              NA
25  adinandra millettii       eurya           pentaphylacaceae
26  eurya muricata            eurya           pentaphylacaceae
27  clerodendrum cyrtophyllum clerodendrum    lamiaceae
28  rubus corchorifolius      rubus           rosaceae
29  calicarpa dichotoma       calicarpa       lamiaceae
30  fraxinus insularis        fraxinus        oleaceae
⋮   ⋮                         ⋮               ⋮
132 symplocos stellaris       symplocos       symplocaceae
133 aralia chinensis          aralia          araliaceae
134 camellia seedling         camellia        theaceae
135 lindera reflexa           NA              NA
136 itea omeiensis            buddleja        scrophulariaceae
137 viburnum setigerum        viburnum        adoxaceae
138 viburnum setigerum        euonymus        celastraceae
139 seedling                  pterostyrax     styracaceae
140 lindera glauca            lindera         lauraceae
141 camellia sinensis         eurya           pentaphylacaceae
142 rhus chinensis            eurya           pentaphylacaceae
143 seedling                  premna          lamiaceae
144 camellia fraterna         itea            iteaceae
145 itea omeiensis            camellia        theaceae
146 quercus phillyreoides     quercus         fagaceae
147 quercus sp.               quercus         fagaceae
148 styrax odoratissimus      styrax          styracaceae
149 unknown sp.               unknown         unknown
150 mussaenda esquirolii      musseanda       rubiaceae
151 centaurea jacea           centaurea       asteraceae
152 not-liquidambar           not-liquidambar NA
153 fern                      fern            polypodiopsida
154 litsea sp.                litsea          lauraceae
155 camellia sp.              camellia        theaceae
156 itea sp.                  itea            iteaceae
157 mussaenda esquirolii      mussaenda       NA
158 mussaenda equifolia       mussaenda       NA
159 viburnum sempervirens     viburnum        adoxaceae
160 phoebe bournei            phoebe          NA
161 machilus sp.              machilus        lauraceae

In [16]:
library(dplyr)
library(stringr)

all_data2 <- all_data |>
  mutate(
    genus = case_when(
		
		species == "fraxinus insularis" ~ "fraxinus",
		species == "euonymus myrianthus" ~ "euonymus",
		species == "aralia chinensis" ~ "aralia",
		str_detect(species, "ilex ficoidea") ~ "ilex",
      str_detect(species, "adinandra millettii") ~ "adinandra",
      species == "alniphyllum fortunei" ~ "alniphyllum",
      species == "buddleja lindleyana" ~ "buddleja",
      str_detect(species, "camellia") ~ "camellia",
      species == "castanopsis sclerophylla" ~ "castanopsis",
      species == "crataegus cuneata" ~ "crataegus",
      species == "eurya muricata" ~ "eurya",
      species == "ilex pubescens" ~ "ilex", # Korrigiert von iley
      species %in% c("itea omeiensis", "itea sp.") ~ "itea",
      species == "lindera reflexa" ~ "lindera",
      species == "liquidambar formosana" ~ "liquidambar",
      str_detect(species, "litsea") ~ "litsea",
      species == "loropetalum chinense" ~ "loropetalum",
      species == "melia azedarach" ~ "melia",
      species == "mussaenda esquirolii" ~ "mussaenda", # Korrigiert von musseanda
      species == "phyllostachys glauca" ~ "phyllostachys",
      species == "premna microphylla" ~ "premna",
      species == "pterostyrax corymbosus" ~ "pterostyrax",
      str_detect(species, "quercus") ~ "quercus",
      str_detect(species, "recruit") ~ NA_character_,
      species == "rhaphiolepis indica" ~ "rhaphiolepis",
      species == "rhododendron simsii" ~ "rhododendron",
      species == "rhus chinensis" ~ "rhus",
      species == "rubus corchorifolius" ~ "rubus",
      species == "schoepfia jasminodora" ~ "schoepfia",
      species == "smilax china" ~ "smilax",
      str_detect(species, "symplocos") ~ "symplocos",
      species == "trema cannabina" ~ "trema",
      species == "viburnum setigerum" ~ "viburnum",
	  species == "musseanda esquirolii" ~ "musseanda",
      TRUE ~ genus
    ),
    family = case_when(
		genus == "musseanda" ~ "rubiaceae",
		genus == "fraxinus" ~ "oleaceae",
		genus == "euonymus" ~ "celastraceae",
		genus == "aralia" ~ "araliaceae",
		genus == "ilex" ~ "aquifoliaceae",
		species == "adinandra millettii" ~ "pentaphylacaceae",
      species == "alniphyllum fortunei" ~ "styracaceae",
      species == "buddleja lindleyana" ~ "scrophulariaceae",
      str_detect(species, "camellia") ~ "theaceae",
      species == "castanopsis sclerophylla" ~ "fagaceae",
      species == "crataegus cuneata" ~ "rosaceae",
      species == "eurya muricata" ~ "pentaphylacaceae",
      species == "ilex pubescens" ~ "aquifoliaceae",
      species %in% c("itea omeiensis", "itea sp.") ~ "iteaceae",
      species == "lindera reflexa" ~ "lauraceae",
      species == "liquidambar formosana" ~ "altingiaceae",
      str_detect(species, "litsea") ~ "lauraceae",
      species == "loropetalum chinense" ~ "hamamelidaceae",
      species == "melia azedarach" ~ "meliaceae",
      species == "mussaenda esquirolii" ~ "rubiaceae",
      species == "phoebe bournei" ~ "lauraceae",
      species == "phyllostachys glauca" ~ "poaceae",
      species == "premna microphylla" ~ "lamiaceae",
      species == "pterostyrax corymbosus" ~ "styracaceae",
      str_detect(species, "quercus") ~ "fagaceae",
      str_detect(species, "recruit") ~ NA_character_,
      species == "rhaphiolepis indica" ~ "rosaceae",
      species == "rhododendron simsii" ~ "ericaceae",
      species == "rhus chinensis" ~ "anacardiaceae",
      species == "rubus corchorifolius" ~ "rosaceae",
      species == "schoepfia jasminodora" ~ "schoepfiaceae",
      species == "smilax china" ~ "smilacaceae",
      str_detect(species, "symplocos") ~ "Symplocaceae",
      species == "trema cannabina" ~ "cannabaceae",
      species == "viburnum setigerum" ~ "adoxaceae",
      TRUE ~ family
    ),
    species = case_when(
      species == "knoopkruid" ~ "knoopkruid sp.",
		species == "styrax odoratissmus" ~ "styrax odoratissimus",
      TRUE ~ species
    )
  )

In [17]:
all_data3 <- all_data2 |>
  mutate(
    growth_form = case_when(
      # Genus-basierte Bedingungen
      genus == "camellia" ~ "shrub/tree",
      genus == "castanopsis" ~ "tree",
      genus == "fraxinus" ~ "tree",
      genus == "ilex" ~ "shrub/tree",
      
      # Species-basierte Bedingungen
      species == "eurya muricata" ~ "shrub/tree",
      species == "itea omeiensis" ~ "shrub/tree",
      species == "lindera reflexa" ~ "shrub/tree",
      species == "liquidambar formosana" ~ "tree",
      species == "litsea cubeba" ~ "shrub/tree",
      species == "loropetalum chinense" ~ "shrub/tree",
      species == "melia azedarach" ~ "tree",
      species == "mussaenda esquirolii" ~ "shrub/tree",
      species == "phyllostachys glauca" ~ "shrub/tree",
      species == "premna microphylla" ~ "shrub/tree",
      species == "pterostyrax corymbosus" ~ "shrub/tree",
      species == "quercus sp." ~ "tree",
      species == "rhaphiolepis indica" ~ "shrub/tree",
      species == "rhododendron simsii" ~ "shrub",
      species == "rhus chinensis" ~ "shrub/tree",
      species == "rubus corchorifolius" ~ "shrub",
      species == "schoepfia jasminodora" ~ "shrub/tree",
      species == "smilax china" ~ "shrub/liana",
      species == "trema cannabina" ~ "shrub/tree",
      species == "adinandra millettii" ~ "shrub/tree",
	  species == "alniphyllum fortunei" ~ "tree",
		species == "buddleja lindleyana" ~ "shrub",
		species == "musseanda esquirolii" ~ "shrub/tree",
      # Fallback: Behalte die existierende growth_form für alle anderen
      TRUE ~ growth_form
    )
  )

In [18]:
all_data3 |>
  distinct(species, genus, family, growth_form) |>
  group_by(species) |>
  filter(n_distinct(growth_form) > 1) |>
  ungroup()

   species     genus           family           growth_form
1  seedling    NA              NA               NA
2  seedling    unknown         unknown          unknown
3  recruit     NA              NA               NA
4  seedling    quercus         fagaceae         tree
5  recruit     NA              NA               unknown
6  NA          NA              NA               NA
7  NA          unknown         unknown          unknown
8  seedling    loropetalum     hamamelidaceae   shrub
9  seedling    litsea          lauraceae        shrub/tree
10 recruit     NA              NA               shrub/tree
11 NA          clerodendrum    lamiaceae        shrub/tree
12 seedling    itea            iteaceae         shrub
13 seedling    buddleja        scrophulariaceae shrub
14 seedling    camellia        theaceae         shrub/tree
15 NA          lindera         lauraceae        shrub/tree
16 NA          machilus        lauraceae        shrub/tree
17 NA          not-liquidambar NA               unknown
18 NA          ilex            aquifoliaceae    shrub/tree
19 seedling    pterostyrax     styracaceae      shrub/tree
20 seedling    premna          lamiaceae        shrub/tree
21 unknown sp. unknown         unknown          unknown
22 unknown sp. unknown         unknown          herb

In [19]:
colnames(all_data3)

 [1] "date"                    "site"
 [3] "plot"                    "subplot"
 [5] "diversity"               "id"
 [7] "species"                 "genus"
 [9] "family"                  "growth_form"
[11] "seed_source_short"       "tot_veg"
[13] "herb_max"                "grass"
[15] "fern"                    "herbaceous"
[17] "woody"                   "open_ground"
[19] "rock"                    "leaflitter"
[21] "leaflitter_dept"         "deadwood"
[23] "moss"                    "notes"
[25] "survival"                "height"
[27] "number_leaves"           "number_herb_damaged"
[29] "percent_hmin"            "percent_hmax"
[31] "number_fungal_damaged"   "percent_fungal"
[33] "percent_fmin"            "percent_fmax"
[35] "number_necrotic_damaged" "percent_necrose"
[37] "percent_nmin"            "percent_nmax"
[39] "notes2"                  "year"
[41] "type"                    "percent_herb"
[43] "saplings"                "seedlings"
[45] "rli"                     "soil_h20_all"
[47] "soil_ph_k_cl_all"        "soil_n_all"
[49] "soil_c_all"              "soil_c_n_all"
[51] "soil_h20"                "soil_ph_k_cl"
[53] "soil_n"                  "soil_c"
[55] "soil_c_n"

In [20]:
all_data4 <- all_data3 |>
  mutate(notes = paste(notes, notes2), notes = str_replace_all(notes, "NA","")) |>
  select(
    # Sampling info
    date, year, site, plot, subplot, type, diversity, id,
    # Taxonomy
    species, genus, family, growth_form, seed_source_short,
    # Vegetation structure
    tot_veg, percent_herb, herb_max, grass, fern, herbaceous, woody, saplings, seedlings,
    # Substrate/ground cover
    open_ground, rock, leaflitter, leaflitter_dept, deadwood, moss,
    # Plant traits & survival
    survival, height, number_leaves,
    # Damage metrics
    number_herb_damaged, percent_hmin, percent_hmax,
    number_fungal_damaged, percent_fungal, percent_fmin, percent_fmax,
    number_necrotic_damaged, percent_necrose, percent_nmin, percent_nmax,
    # Environmental/soil
    rli, soil_h20, soil_ph_k_cl, soil_n, soil_c, soil_c_n,
    # Notes
    notes
  )

In [21]:
all_data3 |> 
 glimpse()

Rows: 4,024
Columns: 55
$ date                    <chr> "2024-05-26", "2024-05-26", "2024-05-26", "202…
$ site                    <chr> "a", "a", "a", "a", "a", "a", "a", "a", "a", "…
$ plot                    <chr> "ac32", "ac32", "ac32", "ac32", "ac32", "ac32"…
$ subplot                 <chr> "ac32-i", "ac32-i", "ac32-i", "ac32-i", "ac32-…
$ diversity               <int> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
$ id                      <chr> "276", "327", "597", "1658", "1520", "1526", "…
$ species                 <chr> "lindera reflexa", "lindera reflexa", "lindera…
$ genus                   <chr> "lindera", "lindera", "lindera", NA, "quercus"…
$ family                  <chr> "lauraceae", "lauraceae", "lauraceae", NA, "fa…
$ growth_form             <chr> "shrub/tree", "shrub/tree", "shrub/tree", NA, …
$ seed_source_short       <chr> "EI", "EI", "EI", NA, NA, NA, "II", "II", "EI"…
$ tot_veg                 <dbl> 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.65, 0.65…
$ herb_max                <int> 72, 72, 72, 72, 72, 72, 71, 71, 85, 85, 95, 95…
$ grass                   <dbl> 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.00, 0.00…
$ fern                    <dbl> 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.10, 0.10…
$ herbaceous              <dbl> 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.35, 0.35…
$ woody                   <dbl> 0.40, 0.40, 0.40, 0.40, 0.40, 0.40, 0.20, 0.20…
$ open_ground             <dbl> 0.30, 0.30, 0.30, 0.30, 0.30, 0.30, 0.25, 0.25…
$ rock                    <dbl> 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.01, 0.01…
$ leaflitter              <dbl> 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.05, 0.05…
$ leaflitter_dept         <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, NA, NA, NA, NA, …
$ deadwood                <dbl> 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00…
$ moss                    <dbl> 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.05, 0.05…
$ notes                   <chr> "big cunninghamia right in the middle (128cm h…
$ survival                <chr> "a", "1", "1", "s", "n", "s", "1", "1", "1", "…
$ height                  <dbl> NA, 70, 86, 6, 52, 5, 44, 86, 120, 91, 103, 10…
$ number_leaves           <dbl> NA, 93, 250, 6, 17, 2, 59, 800, 400, 11, 200, …
$ number_herb_damaged     <int> NA, 14, 0, 3, 12, 0, 24, 8, 40, 11, 40, 40, NA…
$ percent_hmin            <dbl> NA, 0.01, NA, 0.20, 0.05, NA, 0.01, 0.01, 0.01…
$ percent_hmax            <dbl> NA, 0.50, NA, 0.30, 0.30, NA, 0.55, 0.30, 0.50…
$ number_fungal_damaged   <dbl> NA, 9, 3, 0, 6, 0, 3, 10, 20, 0, 10, 10, NA, N…
$ percent_fungal          <dbl> NA, 0.09677419, 0.01200000, 0.00000000, 0.3529…
$ percent_fmin            <dbl> NA, 0.01, 0.05, NA, 0.05, NA, 0.01, 0.05, 0.01…
$ percent_fmax            <dbl> NA, 0.45, 0.15, NA, 0.05, NA, 0.40, 0.20, 0.25…
$ number_necrotic_damaged <int> NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, 0…
$ percent_necrose         <dbl> NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, 0…
$ percent_nmin            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ percent_nmax            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ notes2                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "large…
$ year                    <int> 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2024…
$ type                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ percent_herb            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ saplings                <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ seedlings               <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ rli                     <dbl> 21.786338, 21.786338, 21.786338, 21.786338, 21…
$ soil_h20_all            <dbl> 4.673, 4.673, 4.673, 4.673, 4.673, 4.673, 4.67…
$ soil_ph_k_cl_all        <dbl> 3.735, 3.735, 3.735, 3.735, 3.735, 3.735, 3.73…
$ soil_n_all              <dbl> 0.14042845, 0.14042845, 0.14042845, 0.14042845…
$ soil_c_all              <dbl> 1.7618909, 1.7618909, 1.7618909, 1.7618909, 1.…
$ soil_c_n_all            <dbl> 12.001016, 12.001016, 12.001016, 12.001016, 12…
$ soil_h20                <dbl> 4.805, 4.805, 4.805, 4.805, 4.805, 4.805, 4.80…
$ soil_ph_k_cl            <dbl> 3.785, 3.785, 3.785, 3.785, 3.785, 3.785, 3.78…
$ soil_n                  <dbl> 0.2144261, 0.2144261, 0.2144261, 0.2144261, 0.…
$ soil_c                  <dbl> 3.191298, 3.191298, 3.191298, 3.191298, 3.1912…
$ soil_c_n                <dbl> 14.88641, 14.88641, 14.88641, 14.88641, 14.886…

In [22]:
library(dplyr)
library(stringr)

all_data4 <- all_data3 |>
  mutate(across(where(is.character), ~ str_trim(tolower(.)))) |>
  mutate(notes = paste(notes, notes2), notes = str_replace_all(notes, "NA","")) |>
  select(
    # Sampling info
    date, year, site, plot, subplot, type, diversity, id,
    # Taxonomy
    species, genus, family, growth_form, seed_source_short,
	  # Plant traits & survival
    survival, height, number_leaves,
    # Damage metrics
    number_herb_damaged, percent_hmin, percent_hmax,
    number_fungal_damaged, percent_fungal, percent_fmin, percent_fmax,
    number_necrotic_damaged, percent_necrose, percent_nmin, percent_nmax,
    # Vegetation structure
    tot_veg, percent_herb, herb_max, grass, fern, herbaceous, woody, saplings, seedlings,
    # Substrate/ground cover
    open_ground, rock, leaflitter, leaflitter_dept, deadwood, moss,
    # Environmental/soil
    rli, soil_h20, soil_ph_k_cl, soil_n, soil_c, soil_c_n,
	  soil_h20_all, soil_ph_k_cl_all, soil_n_all, soil_c_all, soil_c_n_all,
    # Notes
    notes
  ) 

all_data4 |> 
  saveRDS(file = "datas_and_notebooks/final_datas/absolute_final_all_data_joined.rds")