In [1]:
library(tidyverse)
library(readxl)

# Get all sheet names for each file
sheets_a <- excel_sheets("datas_and_notebooks/soil_data/SP6_Site_A_CNS_pH_depth_increments-2.xls")
sheets_b <- excel_sheets("datas_and_notebooks/soil_data/SP6_Site_B_CNS_pH_depth_increments.xls")

# Read all sheets into a named list of dataframes for each file
site_a_list <- setNames(
  lapply(sheets_a, function(s) read_excel("datas_and_notebooks/soil_data/SP6_Site_A_CNS_pH_depth_increments-2.xls", sheet = s)),
  sheets_a
)

site_b_list <- setNames(
  lapply(sheets_b, function(s) read_excel("datas_and_notebooks/soil_data/SP6_Site_B_CNS_pH_depth_increments.xls", sheet = s)),
  sheets_b
)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
New names:
• `` -> `...3`
• `` -> `...4`
New names:
• `` -> `...3`
• `` -> `...4`

In [2]:
clean_df <- function(df) {
  df %>%
    janitor::clean_names() %>%
    dplyr::mutate(across(
      where(is.character),
      ~ stringr::str_trim(tolower(.))
    ))
}

In [3]:
a_soils <- site_a_list$'Raw data' |> 
 clean_df()

In [4]:
b_soils <- site_b_list$`Raw data` |> 
 clean_df()

In [19]:
site_a_list$`Columns and data groups`

   Column Header
1  plot_number
2  PTAG
3  sample_num
4  lab_num
5  depth_lb
6  pH_H2O
7  pH_KCl
8  N_t
9  C_t
10 S_t
11 C_N
   Column Definition
1  Plot Letter Code; Datagroup description: Plot name (letter, number code)
2  plot code, BEF research plot name, 6 digits with "p" in front; Datagroup description: Research plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2. Research plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A and B are named according to their position in the original spreadsheet, in which they were designed. They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu. Example: "p205260": "p" means that this is a plot that is specified. "2" means, that we are at site B. Now the coordinates of the south - west corner: "0526". Since "e" is the fifth letter of the alphabet, this is Plot E26. The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site B. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively.; Datagroup description: Research plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). There are three main sites for research plots in the BEF Experiment: Comparative Study Plots (CSP) in the Gutianshan Nature Reserve (29º8'18" – 29º17'29" N, 118º2'14" – 118º11'12" E, Zhejiang Province Southeast China), having a size of 30x30m^2, measured on the ground. Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2. Research plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A (29°07'28.2"N 117°54'27.5"E) and B (29°05'06.8"N 117°55'44.4"E) are named according to their position in the original spreadsheet, in which they were designed. They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu. Example: "p205260": "p" means that this is a plot that is specified. "2" means, that we are at site B. Now the coordinates of the south - west corner: "0526". Since "e" is the fifth letter of the alphabet, this is Plot E26. The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site A. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively. Morover, Plots from the main experiment may be labelled in the more ambiguous form of e.g. A32. This indicates a plat either on Site A (29°07'28.2"N 117°54'27.5"E) or Site B (29°05'06.8"N 117°55'44.4"E) of the main experiment. This value only becomes a unique identifier if supported with the "site" information from another cell. Plots labelled in the form of "1_AO1" or "g1_AO1" or "pilot1_AO1" belong to the "Pilot Experiment" (approx location: 29°06'20.2"N 117°55'12.1"E, Jiangxi Province)
3  field name of the sample; Datagroup description: Helper
4  Laboratory number of laboratory of soil science and geoecology in Tübingen
5  depth (lower boundary) of the sample; Datagroup description: Soil depth
6  pH value, mean from two values determined by H20 method. solutionH20 : soil = 2.5:1; Datagroup description: pH value; Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup); Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
7  pH value, mean from two values determined in 1 M KCL; Datagroup description: pH value; Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup); Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
8  total organic nitrogen content; Datagroup description: Nitrogen; Instrumentation: Elemental Analyzer (derived from datagroup); Instrumentation: Elemental Analyzer (derived from datagroup)
9  total soil organic carbon content; Datagroup description: Carbon content
10 total sulphur content; Datagroup description: Sulphur; Instrumentation: heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup); Instrumentation: heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup); Datagroup description: S content
11 ratio organic carbon/organic nitrogen
   Variable Type Unit
1  category      NA
2  category      NA
3  text          NA
4  number        NA
5  number        cm
6  number        pH
7  number        pH
8  number        Mass-%
9  number        Mass-%
10 number        Mass-%
11 number        ratio
   Instrumentation
1  NA
2  NA
3  NA
4  NA
5  NA
6  electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
7  electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
8  Elemental Analyzer (derived from datagroup)
9  NA
10 heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup)
11 NA
   References Keywords
1  NA         location, Site A
2  NA         location, Site A
3  NA         soil base
4  NA         soil base
5  NA         soil, soil depth
6  NA         pH
7  NA         pH
8  NA         SON, nitrogen
9  NA         SOC, carbon
10 NA         S
11 NA         C/N ratio
   Data Group Title
1  Plot name Main experiment (letter, number code)
2  BEF research plot name
3  Helper
4  Laboratory number of Laboratory of Soil Science and Geoecology in Tübingen
5  Soil depth
6  pH value
7  pH value
8  Nitrogen
9  Carbon
10 Sulphur
11 Carbon Nitrogen ratio
   Data Group Description
1  Plot number according to design spreadsheet. Plots are named according to their location on the original spreadsheet used for treatment design. This has letters from West to East and numbers from North to south. Some plots were moved half a gridcell (1 mu) so be suitable for planting (grid cell loctype). Example: B32
2  Reasearch plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). There are three main sites for research plots in the BEF Experiment: Comparative Study Plots (CSP) in the  Gutianshan Nature Reserve (29º8'18" – 29º17'29" N, 118º2'14" – 118º11'12" E, Zhejiang Province Southeast China), having a size of 30x30m^2, measured on the ground. Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2.  \r\nResearch plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A (29°07'28.2"N 117°54'27.5"E) and B (29°05'06.8"N 117°55'44.4"E) are named according to their position in the original spreadsheet, in which they were designed.  They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu.  Example: "p205260": "p" means that this is a plot that is specified.  "2" means, that we are at site B.  Now the coordinates of the south - west corner: "0526".  Since "e" is the fifth letter of the alphabet, this is Plot E26.   The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site A. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively.\r\nMorover, Plots from the main experiment may be labelled in the more ambiguous  form of e.g. A32. This indicates a plat either on Site A (29°07'28.2"N 117°54'27.5"E) or Site B (29°05'06.8"N 117°55'44.4"E) of the main experiment. This value only becomes a unique identifier if supported with the "site" information from another cell.\r\nPlots labelled in the form of "1_AO1" or "g1_AO1" or "pilot1_AO1" belong to the "Pilot Experiment" (approx location:  29°06'20.2"N 117°55'12.1"E, Jiangxi Province)
3  Helper column to understand other columns in this data set
4  Laboratory number laboratory Scholten, Kühn, Tübingen.
5  Incremental soil depth as opposed to soil horizon, where each horizon could be of differen depth.
6  In case of H2O: samples were air-dried, sieved < 2mm, solutionH20 : soil = 2.5:1 -- in case of KCL: samples were air-dried, sieved < 2mm, solutionKCL : soil = 2.5:1; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity
7  In case of H2O: samples were air-dried, sieved < 2mm, solutionH20 : soil = 2.5:1 -- in case of KCL: samples were air-dried, sieved < 2mm, solutionKCL : soil = 2.5:1; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity
8  Nitrogen concentration
9  measurements of Carbon such as concentrations, pools, amount
10 S content: samples were air-dried, sieved < 2mm, ground using a ball mill, using around 40 mg for measurements with vario EL III (Elementar)
11 Carbon Nitrogen ratio

# Cleaning etc.

In [5]:
a_soils |> 
 glimpse()

Rows: 1,643
Columns: 11
$ plot_number <chr> "x13", "x13", "x13", "x13", "x13", "x13", "l9", "l9", "l9"…
$ ptag        <chr> "p124130", "p124130", "p124130", "p124130", "p124130", "p1…
$ sample_num  <chr> "expa-s-x13-1", "expa-s-x13-2", "expa-s-x13-3", "expa-s-x1…
$ lab_num     <chr> "4858", "4859", "4860", "4861", "4862", "4863", "4864", "4…
$ depth_lb    <chr> "5", "10", "20", "30", "40", "50", "5", "10", "20", "30", …
$ p_h_h2o     <chr> "5.06", "5.04", "5.01", "5", "4.98", "5.01", "5.02", "4.83…
$ p_h_k_cl    <chr> "3.9", "3.87", "3.87", "3.91", "3.94", "3.91", "3.79", "3.…
$ n_t         <chr> "0.24330297112464905", "0.21959595382213593", "0.162739068…
$ c_t         <chr> "3.2993035316467285", "2.8164491653442383", "1.80776166915…
$ s_t         <chr> "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05"…
$ c_n         <chr> "13.560473661279", "12.82559681234132", "11.10834471635714…

In [14]:
a_soils |> 
distinct(ptag)

    ptag
1   p124130
2   p112090
3   p110070
4   p122160
5   p117230
6   p123130
7   p122111
8   p111230
9   p116240
10  p117210
11  p114280
12  p114210
13  p117070
14  p112120
15  p120140
16  p118150
17  p117150
18  p111040
19  p110210
20  p114290
21  p121150
22  p111210
23  p117240
24  p121140
25  p124140
26  p115190
27  p108081
28  p116250
29  p111030
30  p118090
⋮   ⋮
245 p106350
246 p105320
247 p114060
248 p105300
249 p111080
250 p107250
251 p121110
252 p105240
253 p110290
254 p104320
255 p107190
256 p108270
257 p102361
258 p111090
259 p120100
260 p109300
261 p104310
262 p109270
263 p107160
264 p107310
265 p107330
266 p107340
267 p121100
268 p112200
269 p112190
270 p119100
271 p119090
272 p113190
273 p113180
274 p113200

In [8]:
all_data_joined_lg <- readRDS("datas_and_notebooks/final_datas/all_data_joined_lightlogger.rds")

In [12]:
unique(all_data_joined_lg$plot)

 [1] "ac32"  "ae31"  "ae33"  "af21"  "af27"  "ag24"  "ah31"  "ai12"  "ai27"
[10] "ai28"  "aj21"  "ak19"  "al10"  "al11"  "al22"  "an8"   "an9"   "an11"
[19] "an13"  "ao22"  "ao27"  "ap19"  "ap23"  "ap26"  "aq21"  "aq9"   "ar14"
[28] "as10"  "at15"  "awx12" "aw14"  "bg28"  "bi25"  "bj29"  "bm22"  "bm24"
[37] "bm29"  "bm7"   "bn28"  "bn5"   "bo27"  "bo31"  "bq17"  "bq27"  "bq29"
[46] "br29"  "br3"   "bs18"  "bs22"  "bt13"  "bt29"  "bt8"   "bu16"  "bu27"
[55] "bv15"  "bv19"  "bv23"  "bv24"  "bw10"  "bw11"  "bx21"